import { addDays, weekday } from './dates'
import type { Task } from './types'

export function buildSeed(today: string): Task[] {
  const createdAt = new Date().toISOString()
  const otherWeekday = (weekday(today) + 3) % 7
  const later = addDays(today, 3)

  return [
    {
      id: 'seed-sys-mit',
      title: 'Walk the plant: pumps, MCC, backup power',
      section: 'systems',
      isMit: true,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-sys-vfd',
      title: 'Check VFD heat and cabinet filters',
      section: 'systems',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'daily' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-sys-gen',
      title: 'Generator unloaded test run',
      section: 'systems',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'weekly', weekday: otherWeekday },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-sys-once',
      title: 'Replace faded MCC bucket labels',
      section: 'systems',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'once' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-scada-mit',
      title: 'Triage overnight alarm flood',
      section: 'scada',
      isMit: true,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-scada-hist',
      title: 'Verify historian gap fill',
      section: 'scada',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-scada-rtu',
      title: 'Backup RTU configs',
      section: 'scada',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'every_n', n: 7 },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-scada-setpoints',
      title: 'Review setpoint changes with ops',
      section: 'scada',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'weekly', weekday: otherWeekday },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-me-mit',
      title: 'Protect a real lunch break',
      section: 'me',
      isMit: true,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-me-walk',
      title: 'Walk 20 minutes',
      section: 'me',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'daily' },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-me-family',
      title: 'Family check-in text',
      section: 'me',
      isMit: false,
      dueDate: today,
      recurrence: { kind: 'weekly', weekday: otherWeekday },
      completedDates: [],
      createdAt,
    },
    {
      id: 'seed-me-dentist',
      title: 'Schedule dentist',
      section: 'me',
      isMit: false,
      dueDate: later,
      recurrence: { kind: 'once' },
      completedDates: [],
      createdAt,
    },
  ]
}
