import { addDays, weekday } from './dates'
import { newTask } from './task'
import type { Task } from './types'

export function buildSeed(today: string): Task[] {
  const createdAt = new Date().toISOString()
  const otherWeekday = (weekday(today) + 3) % 7
  const later = addDays(today, 3)

  return [
    newTask({
      id: 'seed-sys-mit',
      title: 'Walk the plant: pumps, MCC, backup power',
      description: 'Look, listen, and note anything that smells hot or sounds off.',
      section: 'systems',
      isMit: true,
      priority: 1,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      createdAt,
    }),
    newTask({
      id: 'seed-sys-vfd',
      title: 'Check VFD heat and cabinet filters',
      description: 'Wipe filters if dusty; log cabinet temperature.',
      section: 'systems',
      priority: 2,
      dueDate: today,
      recurrence: { kind: 'daily' },
      createdAt,
    }),
    newTask({
      id: 'seed-sys-gen',
      title: 'Generator unloaded test run',
      description: 'Ten minutes unloaded. Confirm auto-start after.',
      section: 'systems',
      priority: 3,
      dueDate: today,
      recurrence: { kind: 'weekly', weekday: otherWeekday },
      createdAt,
    }),
    newTask({
      id: 'seed-sys-once',
      title: 'Replace faded MCC bucket labels',
      description: 'Print new labels for buckets 3, 7, and 11.',
      section: 'systems',
      priority: 4,
      dueDate: today,
      recurrence: { kind: 'once' },
      createdAt,
    }),
    newTask({
      id: 'seed-scada-mit',
      title: 'Triage overnight alarm flood',
      description: 'Shelve nuisances only after ops agrees.',
      section: 'scada',
      isMit: true,
      priority: 1,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      createdAt,
    }),
    newTask({
      id: 'seed-scada-hist',
      title: 'Verify historian gap fill',
      description: 'Check the last 24h for missing tags after the RTU blip.',
      section: 'scada',
      priority: 2,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      createdAt,
    }),
    newTask({
      id: 'seed-scada-rtu',
      title: 'Backup RTU configs',
      description: 'Copy to the shared drive and the air-gapped stick.',
      section: 'scada',
      priority: 3,
      dueDate: today,
      recurrence: { kind: 'every_n', n: 7 },
      createdAt,
    }),
    newTask({
      id: 'seed-scada-setpoints',
      title: 'Review setpoint changes with ops',
      description: 'Walk through anything changed since last week.',
      section: 'scada',
      priority: 4,
      dueDate: today,
      recurrence: { kind: 'weekly', weekday: otherWeekday },
      createdAt,
    }),
    newTask({
      id: 'seed-me-mit',
      title: 'Protect a real lunch break',
      description: 'Leave the radio. Eat sitting down.',
      section: 'me',
      isMit: true,
      priority: 1,
      dueDate: today,
      recurrence: { kind: 'weekdays' },
      createdAt,
    }),
    newTask({
      id: 'seed-me-walk',
      title: 'Walk 20 minutes',
      description: 'Loop the pond if the weather holds.',
      section: 'me',
      priority: 2,
      dueDate: today,
      recurrence: { kind: 'daily' },
      createdAt,
    }),
    newTask({
      id: 'seed-me-family',
      title: 'Family check-in text',
      description: 'One real sentence, not just a thumbs-up.',
      section: 'me',
      priority: 3,
      dueDate: today,
      recurrence: { kind: 'weekly', weekday: otherWeekday },
      createdAt,
    }),
    newTask({
      id: 'seed-me-dentist',
      title: 'Schedule dentist',
      description: 'Cleaning + the cracked molar follow-up.',
      section: 'me',
      priority: 5,
      dueDate: later,
      recurrence: { kind: 'once' },
      createdAt,
    }),
  ]
}
